### ISSUE TITLE
Rar file broken

### ISSUE THREAD

**Issue by LocutusOfPenguin** [hkdb/VBoxMacSetup#1]
Hi,

downloading from the mentioned Google Drive results in a broken rar-file (using Ubuntu 18.04)

**Comment by hkdb** [comment]
Hi @LocutusOfPenguin,

Thanks for pointing this out! I think this link keeps on changing so I have just changed the instructions to point to the post that keeps the link updated as I am not really the maintainer of this image plus I developed by medium post and this repo partly based on this posts content. Hope this didn't come too late. Sorry for the delay as I have been completely slammed with work. 

https://github.com/hkdb/VBoxMacSetup/tree/v1.1
