### ISSUE TITLE
always return "Something is missing"

### ISSUE THREAD

**Issue by leandross2** [hkdb/VBoxMacSetup#10]
i enter this line in terminal
"./setup.sh -v "MacOS" -r 1920x1080" 
and return the message
"Something is missing... Type "./setup -h" without the quotes to find out more...".
i'm using linux mint 19.1

**Comment by leandross2** [comment]
i'm using linux mint 19.1

**Comment by scope2229** [comment]
im getting the same error with ubuntu 18.04

**Comment by hkdb** [comment]
@leandross2 Not sure if this matters but looks like you are missing a " before 1920x1080...

**Comment by leandross2** [comment]
![image](https://user-images.githubusercontent.com/12846755/64917369-28a44100-d766-11e9-99c8-813a35d31faa.png)

**Comment by edips** [comment]
After deleting this in script, it worked :D 
```
if [ "$#" -le 4 ] && [ "$1" != "-h" ]; then
    echo -e '\nSomething is missing... Type "./setup -h" without the quotes to find out more...\n'
    exit 0
fi
```
MacOS is working on Ubuntu, Thanks!

**Comment by leandross2** [comment]
thank's @edips

**Comment by scope2229** [comment]
changing '-le' to '<' fixes the error. you need 4 params this is asking less than or equal to 4

**Comment by scope2229** [comment]
if you merge the commit i made it will fix it for you.

**Comment by joneldiablo** [comment]
merge is not done right?

**Comment by scope2229** [comment]
No its still showing as -le 4 which is wrong it just needs to be less than 4 not less than or equal to. 

Change the -le to less than and it works maybe also add a greater than 4 to so that exactly 4 params are taken no more no less

**Comment by hkdb** [comment]
Sorry for the late reply guys. Been slammed with work and other things. Just merged a PR that seems to solve the issue. I believe what @scope2229 mentioned is probably the best solution. If you would like to make the change and submit a PR, I will make sure I test it and merge if it all works. Otherwise, I think what's there now will do for what it is. Thanks!
