### ISSUE TITLE
command not working

### ISSUE THREAD

**Issue by scutariutudor** [hkdb/VBoxMacSetup#11]
I gave this command "./setup.sh -v macos -r 1920x1080
" but the response is "Something is missing... Type "./setup -h" without the quotes to find out more..."

**Comment by hkdb** [comment]
@scutariutudor Turns out that the check on number of flags was wrong. No idea why it had worked for me before. Just merged a PR that fixes the problem. Sorry for the late reply. Work has been crazy...
