### ISSUE TITLE
Something is missing

### ISSUE THREAD

**Issue by mkmodi** [hkdb/VBoxMacSetup#13]
Hi,  I am trying to install High Sierra on a ubuntu 18.04 machine. After I run the command  
./setup.sh -v "MacOS" -r 1920x1068 
I get the error: Something is missing... Type "./setup -h" without the quotes to find out more...
I have tried my level best but could not get past this. Help

**Comment by mkmodi** [comment]
I could finally get it running by commenting out the first if statements. Though I did not understand why.

**Comment by hkdb** [comment]
@mkmodi Turns out that the check on number of flags was wrong. No idea why it had worked for me before. Just merged a PR that fixes the problem. Sorry for the late reply. Work has been crazy...
