### ISSUE TITLE
Doesn't Run

### ISSUE THREAD

**Issue by MapGuy11** [hkdb/VBoxMacSetup#18]
I have all the options correctly but the script just error like I don't.

On: POP OS! 19.10

**Comment by MapGuy11** [comment]
You are not going to respond so I close

**Comment by hkdb** [comment]
Sorry @MapGuy11 .... work got quite busy. Hope you found a way out. I also just merged a PR that should fix this issue. Thanks!

**Comment by MapGuy11** [comment]
Not a problem thanks!
