### ISSUE TITLE
MacOS doesn't start

### ISSUE THREAD

**Issue by marcuzy** [hkdb/VBoxMacSetup#4]
Hi! 

I've done all the instructions but seems something has gone wrong. I see only console mode and nothing happens for a pretty long time. Any ideas?

![macosterminal](https://user-images.githubusercontent.com/1289903/52766212-0a078b80-3059-11e9-9173-c5e60a86551a.png)

VirtualBox 5.2.18
Linux Mint 19 Tara

**Comment by hkdb** [comment]
Without knowing more details, my best effort advice would for you to maybe re-download the image from this post: https://techsviewer.com/install-macos-high-sierra-virtualbox-windows/ and go through the steps again. Hope that helps!

**Comment by provokateurin** [comment]
I made a pull request for this issue #7

**Comment by springzfx** [comment]
> I made a pull request for this issue #7

Have the same problem, and this works for me. thanks

**Comment by hkdb** [comment]
What hardware are you guys using? If it's different, then I think we can at least say that this is a fix that works across multiple hardware configs. If we can get more confirmation, it will make me feel more comfortable to merge. Anyone else want to test this? Thanks!

**Comment by hkdb** [comment]
It would also help if all testers included the host OS they are running. Thanks!

**Comment by punkproger** [comment]
The same issue, got critical error of VB system.
My OS: Ubuntu 16.04 LTS.
Trying to up MacOS 10.13.6.
CPU: i7 8700k
GPU: GTX 1080 Ti

Logs are attached.
[VBox.txt](https://github.com/hkdb/VBoxMacSetup/files/3312300/VBox.txt)
![image](https://user-images.githubusercontent.com/22224085/59885935-b1a91780-93c5-11e9-887c-57dc51434402.png)

How to fix this?

**Comment by hkdb** [comment]
If you set the OS type to macOS 64-bit instead of macOS 10.13 High Sierra [64-bit] then it should boot. If that doesn't work, you may have to recreate the VM with the right OS type. I learned this from my test of a PR #7  that I just merged to the develop branch.

**Comment by hkdb** [comment]
if it's because you are not on an intel processor, the fix is here:

https://github.com/hkdb/VBoxMacSetup/releases/tag/v1.2
