### ISSUE TITLE
Virtual Box 6.x Support

### ISSUE THREAD

**Issue by Gustl22** [hkdb/VBoxMacSetup#8]
Does this work for VB 6.x, too? Or will it be supported?
Currently I get that error: 
```
RTR3InitEx failed with rc=-1912 (rc=-1912)
```
Thx in advance!

**Comment by hkdb** [comment]
I am at least unaware of any changes in VB6 that would make this script not work. The error message you are getting seems to be something else:

https://forum.manjaro.org/t/virtualbox-rtr3initex-failed-with-rc-1912-rc-1912/28315

What OS are you running on your host?

**Comment by Gustl22** [comment]
I'm running Ubuntu Disco.

Now I installed Virtualbox 6 again via their repository.
```
wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
add-apt-repository "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian disco contrib"
sudo apt update
sudo apt-get install virtualbox-6.0
```
Then I installed the new extension pack via their wizard when opening VB6.
And now it works flawless. Thanks :)

**Comment by Gustl22** [comment]
You may can update Dependencies in README to also work with VB 6.x

**Comment by hkdb** [comment]
Awesome! Thank you!
